/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
  // Design tokens mapped to CSS variables from globals.css
  background: "var(--background)",
  foreground: "var(--foreground)",
  card: "var(--card)",
  "card-foreground": "var(--card-foreground)",
  popover: "var(--popover)",
  "popover-foreground": "var(--popover-foreground)",
  primary: "var(--primary)",
  "primary-foreground": "var(--primary-foreground)",
  secondary: "var(--secondary)",
  "secondary-foreground": "var(--secondary-foreground)",
  muted: "var(--muted)",
  "muted-foreground": "var(--muted-foreground)",
  accent: "var(--accent)",
  "accent-foreground": "var(--accent-foreground)",
  destructive: "var(--destructive)",
  "destructive-foreground": "var(--destructive-foreground)",
  border: "var(--border)",
  input: "var(--input)",
  ring: "var(--ring)",
  // Sidebar tokens
  sidebar: "var(--sidebar)",
  "sidebar-foreground": "var(--sidebar-foreground)",
  "sidebar-primary": "var(--sidebar-primary)",
  "sidebar-primary-foreground": "var(--sidebar-primary-foreground)",
  "sidebar-accent": "var(--sidebar-accent)",
  "sidebar-accent-foreground": "var(--sidebar-accent-foreground)",
  "sidebar-border": "var(--sidebar-border)",
  "sidebar-ring": "var(--sidebar-ring)",
        golden: {
          50: "#FFFDF3",
          100: "#FFF7D6",
          200: "#FFEFAA",
          300: "#FFE67D",
          400: "#FFDD51",
          500: "#F5C518",
          600: "#D4A90F",
          700: "#B38E08",
          800: "#927305",
          900: "#725902",
        },
      },
    },
  },
  plugins: [],
};
